### ISSUE TITLE
HTTP/2 may send DATA after RST_STREAM

### ISSUE THREAD

**Issue by essen** [ninenines/cowboy#1479]
The function `prepare_data/6` may call `maybe_terminate_stream/3` and send an `RST_STREAM` before returning and sending the data buffered. The stream should be terminated AFTER we flush the buffer.

**Comment by essen** [comment]
The Gun tests `cancel_remote` and `cancel_remote_connect` can be used to reproduce the issue. The tests pass but errors may be logged about this issue. Tracing can otherwise be used to confirm the wrong behavior.

**Comment by essen** [comment]
I ran into this again so I will fix it now.

**Comment by essen** [comment]
Done.

**Comment by huberts90** [comment]
Hi Loïc,
is this issue released in any version? I am facing the issue, where uploading big files ends crash:
```
2023-02-21T08:00:23.216675Z	trace	envoy router	[C147][S11823289556390547815] proxying 16384 bytes
2023-02-21T08:00:23.216678Z	trace	envoy http	[C147][S11823289556390547815] decode data called: filter=envoy.filters.http.upstream_codec status=0
2023-02-21T08:00:23.216681Z	trace	envoy http	[C147][S11823289556390547815] decode data called: filter=envoy.filters.http.router status=3
2023-02-21T08:00:23.216683Z	trace	envoy http2	[C147] about to recv frame type=3, flags=0, stream_id=5
2023-02-21T08:00:23.216686Z	trace	envoy http2	[C147] track inbound frame type=3 flags=0 length=4 padding_length=0
2023-02-21T08:00:23.216690Z	trace	envoy http2	[C147] recv frame type=3
2023-02-21T08:00:23.216693Z	trace	envoy http2	[C147] remote reset: 0
2023-02-21T08:00:23.216696Z	debug	envoy http2	[C147] stream 5 closed: 0
2023-02-21T08:00:23.216699Z	debug	envoy http	[C147][S11823289556390547815] stream reset
...
```
A piece of stack is:
```
[
  13,
  :no_error,
  ...   
  [file: 'lib/upload_service/stream_handler.ex', line: 128]},
  {:cowboy_stream, :terminate, 3,
   [file: '/opt/deps/cowboy/src/cowboy_stream.erl', line: 138]},
  {:cowboy_http2, :terminate_stream_handler, 4,
   [file: '/opt/deps/cowboy/src/cowboy_http2.erl', line: 1200]},
  {:cowboy_http2, :rst_stream_frame, 3,
   [file: '/opt/deps/cowboy/src/cowboy_http2.erl', line: 569]},
  {:cowboy_http2, :parse, 2,
   [file: '/opt/deps/cowboy/src/cowboy_http2.erl', line: 325]},
  {:cowboy_http, :parse, 2,
   [file: '/opt/deps/cowboy/src/cowboy_http.erl', line: 337]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
  ...
]
```
I have been debugging it for days, I thought that maybe it is related to this issue?

**Comment by huberts90** [comment]
I have pulled the latest master version but it still crashes.

**Comment by essen** [comment]
Your crash seems to happen in stream_handler.ex, not in Cowboy.

**Comment by essen** [comment]
The fix is not in a released version in any case but it's in master.

**Comment by huberts90** [comment]
Yes, the stack trace pointed that I did not predict specific terminate function. I handled it but the problem lies itself lies somewhere in http2 stream that is being reset because of `no_error` reason. This is what I get on the client side:
```
2023/02/21 10:07:06 http2: Framer 0xc0001920e0: read HEADERS flags=END_HEADERS stream=3 len=52
2023/02/21 10:07:06 http2: decoded hpack field header field ":status" = "502"
2023/02/21 10:07:06 http2: decoded hpack field header field "content-length" = "87"
2023/02/21 10:07:06 http2: decoded hpack field header field "content-type" = "text/plain"
2023/02/21 10:07:06 http2: decoded hpack field header field "date" = "Tue, 21 Feb 2023 09:07:05 GMT"
2023/02/21 10:07:06 http2: decoded hpack field header field "server" = "istio-envoy"
2023/02/21 10:07:06 http2: Transport received HEADERS flags=END_HEADERS stream=3 len=52
2023/02/21 10:07:06 http2: Framer 0xc0001920e0: read DATA flags=END_STREAM stream=3 len=87 data="upstream connect error or disconnect/reset before headers. reset reason: protocol error"
2023/02/21 10:07:06 http2: Transport received DATA flags=END_STREAM stream=3 len=87 data="upstream connect error or disconnect/reset before headers. reset reason: protocol error"
2023/02/21 10:07:06 http2: Framer 0xc0001920e0: read RST_STREAM stream=3 len=4 ErrCode=NO_ERROR
2023/02/21 10:07:06 http2: Transport received RST_STREAM stream=3 len=4 ErrCode=NO_ERROR
```

**Comment by essen** [comment]
You receive HEADERS, then DATA with FIN flag set, then RST_STREAM with reason NO_ERROR. There's no problem there. Cowboy will reset the stream if the request body was large (or of unknown size) and won't be fully read to avoid taking up too much bandwidth for no good reason.

Anyway this ticket is about DATA being received *after* RST_STREAM so this is not the same.

**Comment by huberts90** [comment]
Thank you for you information. Is any option to turn on debug mode in cowboy to get flow similarly to e.g. https://go.dev/src/net/http/doc.go `http2debug`?

**Comment by huberts90** [comment]
Another option might be to set the expected header to inform cowboy about length. What would be the best key? I tried with `Content-Length`, but no success.
